# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: testworkflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=minTesLogg.trx"
      
    - name: Store Test Result
      uses: actions/upload-artifact@v3.1.2
      with:
        name: mitt-resultat
        path: minTestLogg

approve:

  runs-on: ubuntu-latest
   
    steps:
   
    - name: Gör checkout
      uses: actions/checkout@v3
      
    - name: mitt-test-resultat
      uses: actions/upload-artifact@v3.1.2
      with:
        name: mitt-resultat
        path: minTesLogg      
